image: kopppcappp/kotoed-docker:default

pipelines:
  default:
    - step:
        script:
          - start_postgresql.sh
          - start_buildbot.sh
          - createuser kotoed -U postgres
          - createdb kotoed -U postgres -O kotoed
          - createdb kotoed-test -U postgres -O kotoed
          - export MAVEN_OPTS="-Xms256m -Xmx512m"
          - mvn clean compile test verify
