image: kopppcappp/kotoed-docker:default

pipelines:
  default:
    - step:
        script:
          - start_postgresql.sh
          - start_teamcity.sh
          - createuser kotoed -U postgres
          - createdb kotoed -U postgres -O kotoed
          - createdb kotoed-test -U postgres -O kotoed
          - mvn clean compile test verify
