image: adrienpessu/docker-maven-postgres:latest

pipelines:
  default:
    - step:
        script:
          - createuser kotoed -U postgres
          - createdb kotoed -U postgres -O kotoed
          - mvn clean compile test
