image: kopppcappp/archlinux-maven-postgres:latest

pipelines:
  default:
    - step:
        script:
          - start_postgresql.sh
          - createuser kotoed -U postgres
          - createdb kotoed -U postgres -O kotoed
          - createdb kotoed-test -U postgres -O kotoed
          - mvn clean compile test verify
